name: Deploy React (CRA) to GitHub Pages

on:
  push:
    branches: [ "main" ]     
  workflow_dispatch:          

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

# (Nếu cần biến môi trường khi build, bỏ comment và điền giá trị)
# env:
#   REACT_APP_API_BASE: https://backend-production-bc73.up.railway.app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"     # CRA 5 chạy ổn với Node 18
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build CRA
        run: npm run build

      # Đảm bảo có CNAME cho thoidaiso.info.vn (nếu bạn chưa commit public/CNAME)
      - name: Ensure CNAME
        run: |
          mkdir -p build
          if [ ! -f build/CNAME ]; then echo "thoidaiso.info.vn" > build/CNAME; fi

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
